In [2]:
import os
import json
import pickle
import sympy as sp
import pandas as pd
from IPython.display import display,HTML

In [3]:
with open('../scripts/configs.json','r',encoding='utf-8') as f:
    CONFIGS = json.load(f)
MODELSDIR = CONFIGS['filepaths']['models']
SRCONFIG  = CONFIGS['experiments']['sr']

In [4]:
VARS = {
    'bl':(0,r'\widetilde{\mathrm{B_L}}'),
    'rh':(1,r'\widehat{\mathrm{RH}}'),
    'thetae':(2,r'\widehat{\theta}_{e}'),
    'thetaestar':(3,r'{\widehat{\theta}_{e}^{*}}'),
    'lf':(4,r'\widetilde{\mathrm{LF}}'),
    'shf':(5,r'\widetilde{\mathrm{SHF}}'),
    'lhf':(6,r'\widetilde{\mathrm{LHF}}'),
    'sef':(7,r'\widetilde{\mathrm{SEF}}'),
    'se':(8,r'\widetilde{\mathrm{SE}}'),
    'sdo':(9,r'\widetilde{\mathrm{SDO}}')}

SYMS  = {k:sp.Symbol(k) for k in VARS}
FUNCS = {'min':sp.Min,'max':sp.Max,'abs':sp.Abs,'neg':lambda x:-x,'square':lambda x:x**2,'cube':lambda x:x**3,'exp':sp.exp}
CONSTLABELS = list('ABCDEFGHIJKLMNOPQRSTUVWXYZ')

In [5]:
def term_key(term):
    syms = term.free_symbols
    if not syms: 
        return (99,str(term))
    return (min(VARS.get(s.name,(50,))[0] for s in syms),str(term))

def order_expr(expr):
    if expr.args:
        expr = expr.func(*[order_expr(a) for a in expr.args],evaluate=False)
    if isinstance(expr,sp.Add):
        expr = sp.Add(*sorted(sp.Add.make_args(expr),key=term_key),evaluate=False)
    return expr

def to_latex(expr):
    latex = sp.latex(expr,symbol_names={SYMS[k]:v[1] for k,v in VARS.items()},mul_symbol='dot')
    return ' '.join(latex.replace(r'\left','').replace(r'\right','').split())

In [6]:
_regpath = os.path.join(MODELSDIR,'sr', 'optimized_equations.pkl')
registry = pickle.load(open(_regpath,'rb')) if os.path.exists(_regpath) else {}

In [7]:
rows1,rows2 = [],[]
for name,opt in registry.items():
    eqspec = SRCONFIG['optimizedeqs'].get(name,{})
    desc   = eqspec.get('description',name)
    constkeys = sorted(opt['constants'].keys())
    parts = [f"{CONSTLABELS[i]} = {opt['constants'][k]:.4f}" for i,k in enumerate(constkeys)]
    rows1.append({'Equation':desc,'Constants':',  '.join(parts)})
    constsyms = {k:sp.Symbol(CONSTLABELS[i]) for i,k in enumerate(constkeys)}
    ns = {**SYMS,**FUNCS,**constsyms}
    try:
        form = '$'+to_latex(order_expr(eval(opt['form'],{'__builtins__':{}},ns)))+'$'
    except Exception as e:
        form = f"{opt['form']}  [error: {e}]"
    rows2.append({'Equation':desc,'Form':form})

In [8]:
display(HTML(pd.DataFrame(rows1).set_index('Equation').to_html(escape=False)))

In [9]:
_css = '<style>.eq-tbl td { text-align: left; }</style>'
display(HTML(_css + pd.DataFrame(rows2).set_index('Equation').to_html(escape=False,classes='eq-tbl')))